In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline

In [10]:
df = pd.read_csv("datasets/IMDB Dataset.csv")

In [11]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [12]:
df.shape

(50000, 2)

In [13]:
df.columns

Index(['review', 'sentiment'], dtype='str')

In [45]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [46]:
x = df.review
y = df.sentiment

In [47]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state = 42)

In [48]:
vectorizer = CountVectorizer()

In [49]:
values = vectorizer.fit_transform(xtrain)
# values.toarray()

In [50]:
names = vectorizer.get_feature_names_out()
names

array(['00', '000', '00000000000', ..., 'żmijewski', 'יגאל', 'כרמון'],
      shape=(93003,), dtype=object)

In [51]:
logistic_regression = LogisticRegression()

In [52]:
pipeline = Pipeline(
            steps= [
                ('vectorization',vectorizer),
                ('model',logistic_regression)
            ]
            )

In [57]:
model = GridSearchCV(
                estimator= pipeline,
                param_grid={
                    'vectorization__max_features':[10000,20000,None],
                    'vectorization__stop_words':[None,'english'],
                    'model__penalty':['l1','l2'],
                    'model__solver':['lbfgs','saga'],
                    'model__C':[0.1,1]
                },
                n_jobs=-1,
                verbose = 10,
                cv = 3
)

In [58]:
model.fit(xtrain,ytrain)

Fitting 3 folds for each of 48 candidates, totalling 144 fits

c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
36 fits failed out of a total of 144.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
36 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1147, in fit
    solver = _check_solver(self.solver, penalty, self.dual)
  File "c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py", line 65, in _check_solver
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.86334997 0.8692999  0.86314997 0.86907491 0.86302497 0.8691499
 0.8868999  0.8826999  0.88964992 0.88532493 0.89042492 0.88694992
 0.87094998 0.88014983 0.87129998 0.88122482 0.87159999 0.88154982
        nan        nan        nan        nan        nan        nan
 0.87047498 0.87954983 0.87082497 0.88062481 0.87082498 0.88054982
 0.87667485 0.86782486 0.88049988 0.87472496 0.88282484 0.87807494
 0.87119998 0.88042482 0.87157499 0.88154981 0.87184999 0.88174983]
  warnings.warn(
c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\chara\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('vectorization', CountVectorizer()),
                                       ('model', LogisticRegression())]),
             n_jobs=-1,
             param_grid={'model__C': [0.1, 1], 'model__penalty': ['l1', 'l2'],
                         'model__solver': ['lbfgs', 'saga'],
                         'vectorization__max_features': [10000, 20000, None],
                         'vectorization__stop_words': [None, 'english']},
             verbose=10)

In [59]:
model.cv_results_

{'mean_fit_time': array([  9.90493178,   9.85885588,  10.88490033,   9.50646464,
          9.97531009,   9.18669788,  58.06838353,  44.02214257,
         59.92594838,  43.82379429,  71.23447053,  52.34101534,
         12.26498032,  11.08266449,  12.86542559,  11.70993201,
         14.29729501,  13.32890916,  21.02178367,  16.18271311,
         21.95977847,  18.0839843 ,  26.76949358,  22.9471724 ,
          9.928334  ,   9.01743992,   9.65785336,   8.92509969,
          9.33462079,   8.98598488, 137.01095001, 125.98356136,
        217.81978234, 192.99392573, 275.57736413, 242.81242379,
         11.07060695,  10.40836986,  12.08540686,  10.84320966,
         14.38472684,  12.97821824,  20.60495885,  16.48869117,
         20.64738599,  17.56929668,  24.15306226,  21.22150191]),
 'std_fit_time': array([0.37959011, 0.34693052, 0.09439724, 0.04940961, 0.68713967,
        0.72751291, 0.54807498, 2.10272824, 1.46435343, 1.76532955,
        1.88066215, 2.98680006, 0.17147399, 0.62278157, 0.44313375,
        0.75414459, 0.55746972, 0.21438883, 0.42724726, 0.27346254,
        0.2797565 , 0.75928783, 0.65981345, 0.63809639, 0.28470559,
        0.28350865, 0.24512548, 0.31465898, 0.1770092 , 0.19132652,
        0.8814171 , 2.03358054, 1.48803277, 3.54730959, 1.40207864,
        6.08627271, 0.01782537, 0.2743217 , 0.5429471 , 0.50802806,
        0.76806485, 0.63273666, 0.93210059, 0.39072031, 0.53106013,
        0.53019736, 1.06774287, 1.41278762]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 4.57948383, 4.07916236, 4.81657386, 4.19546326,
        4.80322647, 4.52912688, 4.63873752, 4.25071255, 5.18131495,
        4.28400366, 4.89343071, 4.13276084, 5.04918154, 4.34834019,
        5.01630735, 4.83903972, 4.54670525, 4.17255561, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        4.47211281, 4.00121816, 4.68923275, 3.96626465, 2.05033867,
        2.36826793, 4.52984842, 4.29308184, 4.76493557, 4.28317356,
        4.75528049, 4.20364451, 4.62565653, 4.12381061, 4.77017546,
        4.19364754, 4.12583899, 3.97639449]),
 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.06550684, 0.09347457, 0.31944283, 0.12228843,
        0.30454711, 0.47524218, 0.17969958, 0.12824127, 0.36607969,
        0.35535115, 0.12204785, 0.24140944, 0.14377731, 0.05373695,
        0.10876126, 0.60681512, 0.05137396, 0.09771498, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.19826149, 0.16688679, 0.24203771, 0.06463526, 0.07808887,
        0.07437474, 0.14663558, 0.08439045, 0.18401899, 0.2442836 ,
        0.31104688, 0.28057117, 0.16023907, 0.16097202, 0.26871409,
        0.11789492, 0.14568899, 0.0539884 ]),
 'param_model__C': masked_array(data=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_model__penalty': masked_array(data=['l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1',
                    'l1', 'l1', 'l1', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2',
                    'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l1', 'l1', 'l1',
                    'l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1', 'l1',
                    'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2',
                    'l2', 'l2', 'l2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__solver': masked_array(data=['lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                    'saga', 'saga', 'saga', 'saga', 'saga', 'saga',
                    'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                    'saga', 'saga', 'saga', 'saga', 'saga', 'saga',
                    'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                    'saga', 'saga', 'saga', 'saga', 'saga', 'saga',
                    'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                    'saga', 'saga', 'saga', 'saga', 'saga', 'saga'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_vectorization__max_features': masked_array(data=[10000, 10000, 20000, 20000, None, None, 10000, 10000,
                    20000, 20000, None, None, 10000, 10000, 20000, 20000,
                    None, None, 10000, 10000, 20000, 20000, None, None,
                    10000, 10000, 20000, 20000, None, None, 10000, 10000,
                    20000, 20000, None, None, 10000, 10000, 20000, 20000,
                    None, None, 10000, 10000, 20000, 20000, None, None],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_vectorization__stop_words': masked_array(data=[None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english',
                    None, 'english', None, 'english', None, 'english'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 0.1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l1',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'lbfgs',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 10000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': 20000,
   'vectorization__stop_words': 'english'},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': None},
  {'model__C': 1,
   'model__penalty': 'l2',
   'model__solver': 'saga',
   'vectorization__max_features': None,
   'vectorization__stop_words': 'english'}],
 'split0_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan, 0.86455677, 0.87318134, 0.86425679, 0.87265637,
        0.8640318 , 0.87303135, 0.89103045, 0.88660567, 0.89298035,
        0.88810559, 0.89365532, 0.89013049, 0.87168142, 0.88675566,
        0.8719814 , 0.88848058, 0.87213139, 0.88885556,        nan,
               nan,        nan,        nan,        nan,        nan,
        0.87145643, 0.88615569, 0.87183141, 0.88818059, 0.87168142,
        0.88758062, 0.88285586, 0.87325634, 0.88548073, 0.87648118,
        0.88915554, 0.88053097, 0.8719814 , 0.88750562, 0.8719814 ,
        0.88900555, 0.87243138, 0.88870556]),
 'split1_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan, 0.86132153, 0.87009675, 0.86117153, 0.87039676,
        0.86132153, 0.87032176, 0.88329708, 0.88247206, 0.88637216,
        0.88622216, 0.88779719, 0.88779719, 0.86867172, 0.87917198,
        0.86889672, 0.879997  , 0.86919673, 0.88022201,        nan,
               nan,        nan,        nan,        nan,        nan,
        0.86852171, 0.87849696, 0.86874672, 0.87887197, 0.86859671,
        0.87909698, 0.87144679, 0.86732168, 0.87804695, 0.8760219 ,
        0.88074702, 0.87774694, 0.86904673, 0.87939698, 0.86919673,
        0.88022201, 0.86949674, 0.88022201]),
 'split2_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan, 0.8641716 , 0.86462162, 0.8640216 , 0.8641716 ,
        0.86372159, 0.8640966 , 0.88637216, 0.87902198, 0.88959724,
        0.88164704, 0.88982225, 0.88292207, 0.87249681, 0.87452186,
        0.87302183, 0.87519688, 0.87347184, 0.87557189,        nan,
               nan,        nan,        nan,        nan,        nan,
        0.87144679, 0.87399685, 0.8718968 , 0.87482187, 0.8721968 ,
        0.87497187, 0.87572189, 0.86289657, 0.87797195, 0.87167179,
        0.87857196, 0.8759469 , 0.87257181, 0.87437186, 0.87354684,
        0.87542189, 0.87362184, 0.87632191]),
 'mean_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan, 0.86334997, 0.8692999 , 0.86314997, 0.86907491,
        0.86302497, 0.8691499 , 0.8868999 , 0.8826999 , 0.88964992,
        0.88532493, 0.89042492, 0.88694992, 0.87094998, 0.88014983,
        0.87129998, 0.88122482, 0.87159999, 0.88154982,        nan,
               nan,        nan,        nan,        nan,        nan,
        0.87047498, 0.87954983, 0.87082497, 0.88062481, 0.87082498,
        0.88054982, 0.87667485, 0.86782486, 0.88049988, 0.87472496,
        0.88282484, 0.87807494, 0.87119998, 0.88042482, 0.87157499,
        0.88154981, 0.87184999, 0.88174983]),
 'std_test_score': array([       nan,        nan,        nan,        nan,        nan,
               nan, 0.00144291, 0.00353963, 0.00140226, 0.00358778,
        0.00121115, 0.00374053, 0.00317911, 0.00310022, 0.00269804,
        0.00271195, 0.00242924, 0.00300319, 0.00164501, 0.00504206,
        0.00175164, 0.0054921 , 0.0017853 , 0.00550371,        nan,
               nan,        nan,        nan,        nan,        nan,
        0.00138117, 0.00501935, 0.00146979, 0.00559274, 0.00158961,
        0.00524901, 0.00470622, 0.0042443 , 0.00352213, 0.00216704,
        0.0045637 , 0.00188576, 0.00154154, 0.00541087, 0.00179903,
        0.00562443, 0.00173352, 0.00516975]),
 'rank_test_score': array([37, 37, 37, 37, 37, 37, 34, 30, 35, 32, 36, 31,  4,  7,  2,  5,  1,
         3, 26, 16, 24, 11, 22,  9, 37, 37, 37, 37, 37, 37, 29, 17, 28, 12,
        27, 13, 19, 33, 14, 20,  6, 18, 25, 15, 23, 10, 21,  8],
       dtype=int32)}

In [60]:
model.best_estimator_

Pipeline(steps=[('vectorization', CountVectorizer()),
                ('model', LogisticRegression(C=0.1, penalty='l2'))])

In [61]:
model.best_params_

{'model__C': 0.1,
 'model__penalty': 'l2',
 'model__solver': 'lbfgs',
 'vectorization__max_features': None,
 'vectorization__stop_words': None}

In [62]:
results = pd.DataFrame(model.cv_results_)

In [64]:
results.sort_values(by='rank_test_score')

    mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
16      14.297295      0.557470  ...        0.002429                1
14      12.865426      0.443134  ...        0.002698                2
17      13.328909      0.214389  ...        0.003003                3
12      12.264980      0.171474  ...        0.003179                4
15      11.709932      0.754145  ...        0.002712                5
40      14.384727      0.768065  ...        0.004564                6
13      11.082664      0.622782  ...        0.003100                7
47      21.221502      1.412788  ...        0.005170                8
23      22.947172      0.638096  ...        0.005504                9
45      17.569297      0.530197  ...        0.005624               10
21      18.083984      0.759288  ...        0.005492               11
33     192.993926      3.547310  ...        0.005593               12
35     242.812424      6.086273  ...        0.005249               13
38      12.085407      0.542947  ...        0.003522               14
43      16.488691      0.390720  ...        0.005411               15
19      16.182713      0.273463  ...        0.005042               16
31     125.983561      2.033581  ...        0.005019               17
41      12.978218      0.632737  ...        0.001886               18
36      11.070607      0.017825  ...        0.004706               19
39      10.843210      0.508028  ...        0.002167               20
46      24.153062      1.067743  ...        0.001734               21
22      26.769494      0.659813  ...        0.001785               22
44      20.647386      0.531060  ...        0.001799               23
20      21.959778      0.279757  ...        0.001752               24
42      20.604959      0.932101  ...        0.001542               25
18      21.021784      0.427247  ...        0.001645               26
34     275.577364      1.402079  ...        0.001590               27
32     217.819782      1.488033  ...        0.001470               28
30     137.010950      0.881417  ...        0.001381               29
7       44.022143      2.102728  ...        0.003540               30
11      52.341015      2.986800  ...        0.003741               31
9       43.823794      1.765330  ...        0.003588               32
37      10.408370      0.274322  ...        0.004244               33
6       58.068384      0.548075  ...        0.001443               34
8       59.925948      1.464353  ...        0.001402               35
10      71.234471      1.880662  ...        0.001211               36
28       9.334621      0.177009  ...             NaN               37
29       8.985985      0.191327  ...             NaN               37
26       9.657853      0.245125  ...             NaN               37
27       8.925100      0.314659  ...             NaN               37
1        9.858856      0.346931  ...             NaN               37
0        9.904932      0.379590  ...             NaN               37
4        9.975310      0.687140  ...             NaN               37
5        9.186698      0.727513  ...             NaN               37
25       9.017440      0.283509  ...             NaN               37
24       9.928334      0.284706  ...             NaN               37
2       10.884900      0.094397  ...             NaN               37
3        9.506465      0.049410  ...             NaN               37

[48 rows x 16 columns]

In [66]:
y_pred_train = model.predict(xtrain)

In [67]:
y_pred_test = model.predict(xtest)

In [68]:
print(classification_report(y_pred_train,ytrain))

              precision    recall  f1-score   support

    negative       0.95      0.96      0.96     19908
    positive       0.96      0.95      0.96     20092

    accuracy                           0.96     40000
   macro avg       0.96      0.96      0.96     40000
weighted avg       0.96      0.96      0.96     40000

In [69]:
print(classification_report(y_pred_test,ytest))

              precision    recall  f1-score   support

    negative       0.89      0.90      0.90      4869
    positive       0.91      0.89      0.90      5131

    accuracy                           0.90     10000
   macro avg       0.90      0.90      0.90     10000
weighted avg       0.90      0.90      0.90     10000

In [71]:
y.value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

### count vectorizer:-
* It is a vectorization preprocessing technique , which converts the sentences based text,  into numbers using word Frequency..
* IT accepts only 1D data and if you provide 2D values.. you will not get errors but the output will be not as expected...
* .. and it is only used for smaller dataset..as it counts only the frequency

### TF-IDF Vectorizer : TF X IDF
* : Term Frequency  X Inverse Document Frequency..
* It is a vectorization preprocessing technique , which converts the sentences into numbers using TF and IDF

* TF :- How many times word present/ Total words in a document (row)

* IDF :- Log(N(nrows) / How many times a word is present in a entire Document)
* IT can be used for medium size dataset..not for real time projects..
* we use embeddings for the real time projects...(which are pretrained..)

* Syntax. : from skelarn.feature_extraction.text import CountVectorizer,TF-IDF

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [ ]:
df = pd.read_csv('')
X = df[['v2']]
y = df['v1']

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y, random_state=42 , train_size=0.8)